# Generated by Django 6.0.2 on 2026-02-15 21:04

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('age', models.IntegerField(default=25)),
                ('gender', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('interests', models.JSONField(default=list)),
                ('engagement_style', models.CharField(default='passive', max_length=20)),
                ('session_duration_min', models.IntegerField(default=5)),
                ('session_duration_max', models.IntegerField(default=30)),
                ('posting_frequency', models.CharField(default='daily', max_length=20)),
                ('active_hours_start', models.IntegerField(default=9)),
                ('active_hours_end', models.IntegerField(default=22)),
                ('scroll_speed', models.CharField(default='medium', max_length=20)),
                ('assigned_device', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_package', models.CharField(blank=True, default='', max_length=300)),
                ('timeout', models.FloatField(default=300.0)),
                ('retry_count', models.IntegerField(default=0)),
                ('actions', models.JSONField(default=list)),
                ('source_file', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=8)),
                ('task_name', models.CharField(blank=True, default='', max_length=200)),
                ('device_serial', models.CharField(max_length=200)),
                ('success', models.BooleanField()),
                ('actions_completed', models.IntegerField()),
                ('actions_total', models.IntegerField()),
                ('duration', models.FloatField()),
                ('error', models.TextField(blank=True, null=True)),
                ('screenshot_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.persona')),
            ],
            options={
                'ordering': ['service_name'],
                'unique_together': {('persona', 'service_name')},
            },
        ),
    ]
