# Generated by Django 6.0.2 on 2026-02-15 22:50

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('device_serial', models.CharField(blank=True, default='', max_length=200)),
                ('trigger_type', models.CharField(choices=[('cron', 'Cron'), ('interval', 'Interval'), ('once', 'One-time')], max_length=10)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=200)),
                ('interval_seconds', models.IntegerField(default=0)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('respect_active_hours', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.persona')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueuedRun',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('device_serial', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='queued', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.persona')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taskresult')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_runs', to='api.task')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='api.scheduledtask')),
            ],
            options={
                'ordering': ['-priority', 'queued_at'],
            },
        ),
    ]
