# Generated by Django 4.2.28 on 2026-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scheduledtask_queuedrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='is_warming',
            field=models.BooleanField(default=False),
        ),
    ]
