# Generated by Django 4.2.28 on 2026-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scheduledtask_is_warming'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='background_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persona',
            name='content_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persona',
            name='niche',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='tone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
