# Generated by Django 4.2.28 on 2026-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_persona_background_story_persona_content_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('persona_enrichment', 'Persona Enrichment'), ('vision', 'Vision & Recovery'), ('comment_generation', 'Comment Generation'), ('content_generation', 'Content Generation')], max_length=50, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('max_tokens', models.IntegerField(default=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
