# Generated by Django 4.2.28 on 2026-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_llmconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=500)),
            ],
        ),
    ]
