# Generated by Django 6.0.2 on 2026-02-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_providerapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='archetype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='artist_knowledge_depth',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='bio_template',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='comment_style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='persona',
            name='content_behavior',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='persona',
            name='engagement_pattern',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='persona',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='persona',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='music_discovery_style',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='profile_aesthetic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='username_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
