# Generated by Django 4.2.28 on 2026-02-16 19:08

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_persona_archetype_persona_artist_knowledge_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='extraction_data',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('artist_name', models.CharField(max_length=200)),
                ('harvest_type', models.CharField(max_length=20)),
                ('target_count', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('profiles_harvested', models.IntegerField(default=0)),
                ('device_serial', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_jobs', to='api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestedProfile',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('source_type', models.CharField(max_length=20)),
                ('source_artist', models.CharField(max_length=200)),
                ('profile_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('validated', 'Validated'), ('used', 'Used'), ('discarded', 'Discarded')], default='raw', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=500)),
                ('harvested_at', models.DateTimeField(auto_now_add=True)),
                ('harvest_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.harvestjob')),
            ],
            options={
                'ordering': ['-harvested_at'],
            },
        ),
    ]
