# Generated by Django 4.2.28 on 2026-02-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_taskresult_extraction_data_harvestjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestjob',
            name='geographic_area',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
