# Generated by Django 4.2.28 on 2026-02-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_harvestjob_geographic_area_harvestjob_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestjob',
            name='task',
        ),
        migrations.DeleteModel(
            name='HarvestedProfile',
        ),
        migrations.DeleteModel(
            name='HarvestJob',
        ),
    ]
