# Generated by Django 4.2.28 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_drop_harvest_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='target_artist',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
