# Generated by Django 4.2.28 on 2026-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_project_model_and_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='max_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('warming', 'Warming'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='target_artist',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='target_persona_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='target_platform',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
