# Generated by Django 4.2.28 on 2026-02-17 20:33

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expand_project_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('social_handles', models.JSONField(blank=True, default=dict)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('raw_profile_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('researching', 'Researching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='purpose',
            field=models.CharField(choices=[('persona_enrichment', 'Persona Enrichment'), ('vision', 'Vision & Recovery'), ('comment_generation', 'Comment Generation'), ('content_generation', 'Content Generation'), ('artist_research', 'Artist Research')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='artist_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.artistprofile'),
        ),
    ]
