# Generated by Django 6.0.2 on 2026-02-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_artistprofile_alter_llmconfig_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='social_handles',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='spotify_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tiktok_handle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
