# Generated by Django 4.2.28 on 2026-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_artistprofile_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='api_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='scraped_comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='scraping_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('scraping', 'Scraping'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
