# Generated by Django 4.2.28 on 2026-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_scraped_comments_api_data_to_artistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
