# Generated by Django 6.0.2 on 2026-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
