# Generated by Django 6.0.2 on 2026-02-19 02:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('device_serial', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='instagram', max_length=50)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('error', 'Error'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('current_action', models.CharField(blank=True, default='', max_length=200)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('api_port', models.IntegerField(default=8080)),
                ('proxy_url', models.URLField(blank=True, default='', max_length=500)),
                ('actions_today', models.IntegerField(default=0)),
                ('total_actions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.persona')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'device_serial')},
            },
        ),
    ]
