# Generated by Django 6.0.2 on 2026-02-19 02:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='device_serial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='agent',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='api.persona'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('idle', 'Idle'), ('busy', 'Busy'), ('error', 'Error'), ('offline', 'Offline')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='instagram', max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('warming', 'Warming'), ('assigned', 'Assigned'), ('banned', 'Banned'), ('cooldown', 'Cooldown')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('warming_started_at', models.DateTimeField(blank=True, null=True)),
                ('warming_days_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'username')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='api.account'),
        ),
    ]
