# Generated by Django 6.0.2 on 2026-02-19 21:13

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_agent_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('android_version', models.CharField(blank=True, default='', max_length=50)),
                ('sdk_version', models.IntegerField(default=0)),
                ('bay', models.CharField(blank=True, default='', max_length=100)),
                ('slot', models.CharField(blank=True, default='', max_length=100)),
                ('location_label', models.CharField(blank=True, default='', max_length=200)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('error', 'Error'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='api.device'),
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.CharField(default=api.models._short_uuid, max_length=8, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('testing', 'Testing')], default='active', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('host', 'port')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='api.proxy'),
        ),
    ]
